Fix for CxHxW when image is called with ndim=2
Summary:
This commit fixes the following exception, occurring when `image` is called with a 2d array, such as `vis.image(np.ones((10,10)))`. The error is debris from the CxHxW changes.

```
>>> import visdom
>>> import numpy as np
>>> vis = visdom.Visdom()
>>> vis.image(np.ones((10,10)))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/PIL/Image.py", line 2195, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 30), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/visdom/__init__.py", line 179, in result
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/visdom/__init__.py", line 318, in image
    im = Image.fromarray(img)
  File "/usr/local/lib/python3.5/site-packages/PIL/Image.py", line 2198, in fromarray
    raise TypeError("Cannot handle this data type")
TypeEr
Closes https://github.com/facebookresearch/visdom/pull/50

Differential Revision: D4790583

Pulled By: ajabri

fbshipit-source-id: 2a0dc883646b97abf6a80fa9a553fbff31db9d61