py: use binary flag in from_t7
Summary:
This fixes a regression introduced in 1753e20f4ba805cb94d3646d472c53bc8d990a2a. At least on Python 3.5, files need to be opened with the binary flag to be able to read/write `bytes` objects from/to them.

I guess this commit was only tested on Python 2.7, where there is no distinction between text and binary files.

A typical backtrace looks like this:
```
Traceback (most recent call last):
  File "/home/schwarzm/.local/lib/python3.5/site-packages/visdom-0.1.6.3-py3.5.egg/visdom/server.py", line 312, in post
    req, endpoint = self.func(req)
  File "/home/schwarzm/.local/lib/python3.5/site-packages/visdom-0.1.6.3-py3.5.egg/visdom/server.py", line 299, in func
    kwargs[k] = unpack_lua(v)
  File "/home/schwarzm/.local/lib/python3.5/site-packages/visdom-0.1.6.3-py3.5.egg/visdom/server.py", line 275, in unpack_lua
    return visdom.from_t7(req_args['val'], b64=True)
  File "/home/schwarzm/.local/lib/python3.5/site-packages/visdom-0.1.6.3-py3.5.egg/visdom/__init__.py", line 66, in from_t7
    ff.write(t)
TypeError: write() argument must be str, not bytes
```
Closes https://github.com/facebookresearch/visdom/pull/215

Differential Revision: D6485461

Pulled By: JackUrb

fbshipit-source-id: 61d385a6da5959733cc4ab20c070b6fc56f7c9a2