Fixes for Python3
Summary:
This PR fixes 3 issues that showed up when I ran `examples/demo.py` with Python3.5:

Commit fffb54f solves
```
Traceback (most recent call last):
  File "example/demo.py", line 67, in <module>
    markercolor=np.floor(np.random.random((2, 3)) * 255),
  File "/usr/local/lib/python3.5/site-packages/visdom/__init__.py", line 356, in scatter
    opts['markercolor'], X, Y, K)
  File "/usr/local/lib/python3.5/site-packages/visdom/__init__.py", line 97, in _markerColorCheck
    markercolor = ['#%x%x%x' % (i[0], i[1], i[2]) for i in mc]
  File "/usr/local/lib/python3.5/site-packages/visdom/__init__.py", line 97, in <listcomp>
    markercolor = ['#%x%x%x' % (i[0], i[1], i[2]) for i in mc]
TypeError: %x format: an integer is required, not numpy.float64
```

Commit 02bf99b solves (this was actually a bug, not a Python3 issue)
```
Traceback (most recent call last):
  File "example/demo.py", line 84, in <module>
    name='new_trace',
  File "/usr/local/lib/python3.5/site-packages/visdom/__init__.py",
Closes https://github.com/facebookresearch/visdom/pull/4

Reviewed By: justinchiu

Differential Revision: D4725266

Pulled By: ajabri

fbshipit-source-id: 03f2020a5fdd81352e5326d5fc4389e1b5530f0a